from pathlib import Path
import unittest


class KillTeamSetupLuaBridgeSourceTests(unittest.TestCase):
    def test_setup_bridge_exposes_placement_only_actions(self) -> None:
        source = Path("tts_killteam_setup_global.lua").read_text(encoding="utf-8")

        self.assertIn('local MCP_BRIDGE_VERSION = "2026-08-01-setup-placement-v6-pivot-reconcile"', source)
        self.assertIn("function onLoad()", source)
        self.assertIn("function onChat(message, sender)", source)
        self.assertIn('event = "chat_message"', source)
        self.assertIn("mcp_forward_chat(message, sender)", source)
        self.assertIn('local MCP_HTTP_CHAT_URL = "http://127.0.0.1:8765/chat"', source)
        self.assertIn("WebRequest.custom(", source)
        self.assertIn('message = raw_message', source)
        self.assertIn("printToAll(text", source)
        self.assertIn("MCP_HANDLERS.setup_ping", source)
        self.assertIn("MCP_HANDLERS.setup_list_objects", source)
        self.assertIn("MCP_HANDLERS.killteam_save_131_setup_objects", source)
        self.assertIn("MCP_HANDLERS.setup_place_model", source)
        self.assertIn("MCP_HANDLERS.move_object", source)
        self.assertIn("bounds = safe_bounds", source)
        self.assertIn("scale = safe_scale", source)
        self.assertIn('object_type == "layoutzone"', source)
        self.assertIn('object_type == "layout"', source)
        self.assertIn('object_type == "scriptingtrigger"', source)
        self.assertIn("local function mcp_bounds_box", source)
        self.assertIn("local function mcp_is_setup_support_surface", source)
        self.assertIn('normalized == "kt_mission_terrain"', source)
        self.assertIn('normalized == "entity=terrain"', source)
        self.assertIn('normalized == "blocks_los=true"', source)
        self.assertIn('return explicit_terrain and mcp_bounds_box(obj) ~= nil', source)
        self.assertNotIn("MCP_HANDLERS.killteam_deployment_test_objects(args, request_id)", source)
        self.assertIn("return MCP_HANDLERS.setup_list_objects(args, request_id)", source)
        self.assertIn("local function mcp_setup_matches_filters", source)
        self.assertIn("args = mcp_json_safe(args)", source)
        self.assertIn("local function mcp_is_operative_figurine", source)
        self.assertIn("local function mcp_is_setup_relevant_object", source)
        self.assertIn('if live_guid ~= nil and tostring(live_guid) ~= "" and tostring(live_guid) ~= "-1" and mcp_setup_matches_filters(obj, args) then', source)
        self.assertIn("setup placement requires an Operative figurine; got", source)
        self.assertIn("printToAll(\"Kill Team setup placement bridge loaded.\"", source)
        self.assertIn("printToAll(\"Kill Team setup placement bridge is active.\"", source)
        self.assertIn("print(\"[tts-mcp-response]\"", source)
        self.assertIn("Wait.frames(function()", source)
        self.assertIn("setPositionSmooth", source)
        self.assertIn("setPosition(", source)

    def test_setup_bridge_logs_raw_and_normalized_move_types(self) -> None:
        source = Path("tts_killteam_setup_global.lua").read_text(encoding="utf-8")

        self.assertIn("local function mcp_type_name", source)
        self.assertIn("local function mcp_setup_request_summary", source)
        self.assertIn("local function mcp_setup_position_table", source)
        self.assertIn('print(mcp_setup_request_summary(args, request_id, action, "pre"))', source)
        self.assertIn('print(mcp_setup_request_summary(args, request_id, action, "post"))', source)
        self.assertIn('MCP_HANDLERS.setup_place_model = function(args, request_id)', source)
        self.assertIn('MCP_HANDLERS.move_object = function(args, request_id)', source)
        self.assertIn('return mcp_setup_place_model(args, request_id, "move_object")', source)
        self.assertIn('error("position must contain numeric x, y, and z values; "', source)
        self.assertIn("setup placement requires live bounds;", source)
        self.assertIn("local support_height = nil", source)
        self.assertIn("local support_guids = {}", source)
        self.assertIn("local pivot_to_bottom_y", source)
        self.assertIn("bounds = actual_bounds", source)
        self.assertIn("requested_position = requested_position", source)
        self.assertIn("mcp_is_setup_support_surface(other)", source)
        self.assertIn("local function mcp_is_setup_objective", source)
        self.assertIn("setup placement intersects an existing model or objective", source)
